package com.kalynx.simplyabinaryserializer.serializer;

import com.kalynx.simplyabinaryserializer.Serializer;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Binary serialization controller - handles ONLY write operations.
 * This class has no knowledge of deserialization logic.
 *
 * Design philosophy:
 * - One-way operation: Object → bytes
 * - No references to deserializer classes
 * - Optimized for write performance
 *
 * @param <T> The type this serializer handles
 */
public class BinarySerializer<T> implements Serializer<T> {

    private final WriterGenerator.PrimitiveWriter<T> writer;
    private final FastByteWriter byteWriter;
    private final int estimatedSize;

    public BinarySerializer(Class<T> targetClass) throws Throwable {
        this.byteWriter = new FastByteWriter();

        // Analyze fields and filter for primitives only
        Field[] primitiveFields = analyzePrimitiveFields(targetClass);

        // Generate optimized writer using WriterGenerator
        WriterGenerator generator = new WriterGenerator();
        this.writer = generator.generatePrimitiveWriter(targetClass, primitiveFields);
        this.estimatedSize = generator.estimatePrimitiveSize(primitiveFields);
    }

    /**
     * Analyzes the target class and extracts all primitive fields.
     */
    private Field[] analyzePrimitiveFields(Class<T> clazz) {
        List<Field> primitiveFields = new ArrayList<>();

        for (Field field : clazz.getDeclaredFields()) {
            // Skip static and transient fields
            if (Modifier.isStatic(field.getModifiers()) || Modifier.isTransient(field.getModifiers())) {
                continue;
            }

            // Only include primitive fields
            if (field.getType().isPrimitive()) {
                field.setAccessible(true);
                primitiveFields.add(field);
            }
        }

        return primitiveFields.toArray(new Field[0]);
    }

    /**
     * Serialize an object to bytes using generated bytecode writer.
     *
     * @param obj The object to serialize
     * @return Serialized byte array
     * @throws Throwable if serialization fails
     */
    @Override
    public byte[] serialize(T obj) throws Throwable {
        if (obj == null) {
            return new byte[0];
        }

        // Reset writer with estimated size
        byteWriter.reset(estimatedSize);

        // Use generated writer for optimal performance
        writer.write(byteWriter, obj);

        return byteWriter.toByteArray();
    }
}