package com.kalynx.simplyabinaryserializer.testutil;

import java.util.List;

/**
 * Common test data classes used across serializer and deserializer tests.
 * All classes are public with public fields to allow generated bytecode access.
 */
public class TestDataClasses {

    // Individual primitive type test classes

    public static class ByteObject {
        public byte value;
        public ByteObject() {}
        public ByteObject(byte value) { this.value = value; }
    }

    public static class ShortObject {
        public short value;
        public ShortObject() {}
        public ShortObject(short value) { this.value = value; }
    }

    public static class IntObject {
        public int value;
        public IntObject() {}
        public IntObject(int value) { this.value = value; }
    }

    public static class LongObject {
        public long value;
        public LongObject() {}
        public LongObject(long value) { this.value = value; }
    }

    public static class FloatObject {
        public float value;
        public FloatObject() {}
        public FloatObject(float value) { this.value = value; }
    }

    public static class DoubleObject {
        public double value;
        public DoubleObject() {}
        public DoubleObject(double value) { this.value = value; }
    }

    public static class BooleanObject {
        public boolean value;
        public BooleanObject() {}
        public BooleanObject(boolean value) { this.value = value; }
    }

    public static class CharObject {
        public char value;
        public CharObject() {}
        public CharObject(char value) { this.value = value; }
    }

    // Composite test classes

    public static class AllPrimitivesObject {
        public byte byteVal;
        public short shortVal;
        public int intVal;
        public long longVal;
        public float floatVal;
        public double doubleVal;
        public boolean boolVal;
        public char charVal;

        public AllPrimitivesObject() {}

        public AllPrimitivesObject(byte b, short s, int i, long l, float f, double d, boolean bool, char c) {
            this.byteVal = b;
            this.shortVal = s;
            this.intVal = i;
            this.longVal = l;
            this.floatVal = f;
            this.doubleVal = d;
            this.boolVal = bool;
            this.charVal = c;
        }
    }

    public static class SingleIntObject {
        public int value;
        public SingleIntObject() {}
        public SingleIntObject(int value) { this.value = value; }
    }

    public static class MultipleIntsObject {
        public int first;
        public int second;
        public int third;

        public MultipleIntsObject() {}

        public MultipleIntsObject(int first, int second, int third) {
            this.first = first;
            this.second = second;
            this.third = third;
        }
    }

    public static class LongValuesObject {
        public long min;
        public long max;
        public long zero;

        public LongValuesObject() {}

        public LongValuesObject(long min, long max, long zero) {
            this.min = min;
            this.max = max;
            this.zero = zero;
        }
    }

    public static class FloatValuesObject {
        public float floatValue;
        public double doubleValue;

        public FloatValuesObject() {}

        public FloatValuesObject(float floatValue, double doubleValue) {
            this.floatValue = floatValue;
            this.doubleValue = doubleValue;
        }
    }

    public static class BooleanValuesObject {
        public boolean trueValue;
        public boolean falseValue;

        public BooleanValuesObject() {}

        public BooleanValuesObject(boolean trueValue, boolean falseValue) {
            this.trueValue = trueValue;
            this.falseValue = falseValue;
        }
    }

    // Test class with mixed field types (for validation testing)
    public static class MixedFieldsObject {
        public int primitiveField;
        public String nonPrimitiveField;

        public MixedFieldsObject() {}

        public MixedFieldsObject(int primitiveField, String nonPrimitiveField) {
            this.primitiveField = primitiveField;
            this.nonPrimitiveField = nonPrimitiveField;
        }
    }

    // Prevent instantiation
    private TestDataClasses() {}

    // ========== List Test Classes ==========

    public static class IntegerListObject {
        public List<Integer> values;

        public IntegerListObject() {}

        public IntegerListObject(List<Integer> values) {
            this.values = values;
        }
    }

    public static class StringListObject {
        public List<String> strings;

        public StringListObject() {}

        public StringListObject(List<String> strings) {
            this.strings = strings;
        }
    }

    public static class LongListObject {
        public List<Long> values;

        public LongListObject() {}

        public LongListObject(List<Long> values) {
            this.values = values;
        }
    }

    public static class DoubleListObject {
        public List<Double> values;

        public DoubleListObject() {}

        public DoubleListObject(List<Double> values) {
            this.values = values;
        }
    }

    public static class BooleanListObject {
        public List<Boolean> values;

        public BooleanListObject() {}

        public BooleanListObject(List<Boolean> values) {
            this.values = values;
        }
    }

    public static class MixedPrimitiveAndListObject {
        public int intValue;
        public List<Integer> intList;

        public MixedPrimitiveAndListObject() {}

        public MixedPrimitiveAndListObject(int intValue, List<Integer> intList) {
            this.intValue = intValue;
            this.intList = intList;
        }
    }

    public static class AllPrimitivesWithListsObject {
        public byte byteVal;
        public List<Integer> intList;
        public long longVal;
        public List<String> stringList;
        public boolean boolVal;

        public AllPrimitivesWithListsObject() {}

        public AllPrimitivesWithListsObject(byte byteVal, List<Integer> intList, long longVal, List<String> stringList, boolean boolVal) {
            this.byteVal = byteVal;
            this.intList = intList;
            this.longVal = longVal;
            this.stringList = stringList;
            this.boolVal = boolVal;
        }
    }
}

