package com.kalynx.simplyabinaryserializer.testutil;

import java.util.List;
import java.util.Map;

/**
 * Common test data classes used across serializer and deserializer tests.
 * All classes are public with public fields to allow generated bytecode access.
 */
public class TestDataClasses {

    // Individual primitive type test classes

    public static class ByteObject {
        public byte value;
        public ByteObject() {}
        public ByteObject(byte value) { this.value = value; }
    }

    public static class ShortObject {
        public short value;
        public ShortObject() {}
        public ShortObject(short value) { this.value = value; }
    }

    public static class IntObject {
        public int value;
        public IntObject() {}
        public IntObject(int value) { this.value = value; }
    }

    public static class LongObject {
        public long value;
        public LongObject() {}
        public LongObject(long value) { this.value = value; }
    }

    public static class FloatObject {
        public float value;
        public FloatObject() {}
        public FloatObject(float value) { this.value = value; }
    }

    public static class DoubleObject {
        public double value;
        public DoubleObject() {}
        public DoubleObject(double value) { this.value = value; }
    }

    public static class BooleanObject {
        public boolean value;
        public BooleanObject() {}
        public BooleanObject(boolean value) { this.value = value; }
    }

    public static class CharObject {
        public char value;
        public CharObject() {}
        public CharObject(char value) { this.value = value; }
    }

    // Composite test classes

    public static class AllPrimitivesObject {
        public byte byteVal;
        public short shortVal;
        public int intVal;
        public long longVal;
        public float floatVal;
        public double doubleVal;
        public boolean boolVal;
        public char charVal;

        public AllPrimitivesObject() {}

        public AllPrimitivesObject(byte b, short s, int i, long l, float f, double d, boolean bool, char c) {
            this.byteVal = b;
            this.shortVal = s;
            this.intVal = i;
            this.longVal = l;
            this.floatVal = f;
            this.doubleVal = d;
            this.boolVal = bool;
            this.charVal = c;
        }
    }

    public static class SingleIntObject {
        public int value;
        public SingleIntObject() {}
        public SingleIntObject(int value) { this.value = value; }
    }

    public static class MultipleIntsObject {
        public int first;
        public int second;
        public int third;

        public MultipleIntsObject() {}

        public MultipleIntsObject(int first, int second, int third) {
            this.first = first;
            this.second = second;
            this.third = third;
        }
    }

    public static class LongValuesObject {
        public long min;
        public long max;
        public long zero;

        public LongValuesObject() {}

        public LongValuesObject(long min, long max, long zero) {
            this.min = min;
            this.max = max;
            this.zero = zero;
        }
    }

    public static class FloatValuesObject {
        public float floatValue;
        public double doubleValue;

        public FloatValuesObject() {}

        public FloatValuesObject(float floatValue, double doubleValue) {
            this.floatValue = floatValue;
            this.doubleValue = doubleValue;
        }
    }

    public static class BooleanValuesObject {
        public boolean trueValue;
        public boolean falseValue;

        public BooleanValuesObject() {}

        public BooleanValuesObject(boolean trueValue, boolean falseValue) {
            this.trueValue = trueValue;
            this.falseValue = falseValue;
        }
    }

    // Test class with mixed field types (for validation testing)
    public static class MixedFieldsObject {
        public int primitiveField;
        public String nonPrimitiveField;

        public MixedFieldsObject() {}

        public MixedFieldsObject(int primitiveField, String nonPrimitiveField) {
            this.primitiveField = primitiveField;
            this.nonPrimitiveField = nonPrimitiveField;
        }
    }

    // Prevent instantiation
    private TestDataClasses() {}

    // ========== List Test Classes ==========

    public static class IntegerListObject {
        public List<Integer> values;

        public IntegerListObject() {}

        public IntegerListObject(List<Integer> values) {
            this.values = values;
        }
    }

    public static class StringListObject {
        public List<String> strings;

        public StringListObject() {}

        public StringListObject(List<String> strings) {
            this.strings = strings;
        }
    }

    public static class LongListObject {
        public List<Long> values;

        public LongListObject() {}

        public LongListObject(List<Long> values) {
            this.values = values;
        }
    }

    public static class DoubleListObject {
        public List<Double> values;

        public DoubleListObject() {}

        public DoubleListObject(List<Double> values) {
            this.values = values;
        }
    }

    public static class BooleanListObject {
        public List<Boolean> values;

        public BooleanListObject() {}

        public BooleanListObject(List<Boolean> values) {
            this.values = values;
        }
    }

    public static class MixedPrimitiveAndListObject {
        public int intValue;
        public List<Integer> intList;

        public MixedPrimitiveAndListObject() {}

        public MixedPrimitiveAndListObject(int intValue, List<Integer> intList) {
            this.intValue = intValue;
            this.intList = intList;
        }
    }

    public static class AllPrimitivesWithListsObject {
        public byte byteVal;
        public List<Integer> intList;
        public long longVal;
        public List<String> stringList;
        public boolean boolVal;

        public AllPrimitivesWithListsObject() {}

        public AllPrimitivesWithListsObject(byte byteVal, List<Integer> intList, long longVal, List<String> stringList, boolean boolVal) {
            this.byteVal = byteVal;
            this.intList = intList;
            this.longVal = longVal;
            this.stringList = stringList;
            this.boolVal = boolVal;
        }
    }

    // Array test classes

    public static class IntArrayObject {
        public int[] values;
        public IntArrayObject() {}
        public IntArrayObject(int[] values) { this.values = values; }
    }

    public static class LongArrayObject {
        public long[] values;
        public LongArrayObject() {}
        public LongArrayObject(long[] values) { this.values = values; }
    }

    public static class DoubleArrayObject {
        public double[] values;
        public DoubleArrayObject() {}
        public DoubleArrayObject(double[] values) { this.values = values; }
    }

    public static class FloatArrayObject {
        public float[] values;
        public FloatArrayObject() {}
        public FloatArrayObject(float[] values) { this.values = values; }
    }

    public static class ShortArrayObject {
        public short[] values;
        public ShortArrayObject() {}
        public ShortArrayObject(short[] values) { this.values = values; }
    }

    public static class ByteArrayObject {
        public byte[] values;
        public ByteArrayObject() {}
        public ByteArrayObject(byte[] values) { this.values = values; }
    }

    public static class BooleanArrayObject {
        public boolean[] values;
        public BooleanArrayObject() {}
        public BooleanArrayObject(boolean[] values) { this.values = values; }
    }

    public static class CharArrayObject {
        public char[] values;
        public CharArrayObject() {}
        public CharArrayObject(char[] values) { this.values = values; }
    }

    public static class AllPrimitiveArraysObject {
        public int[] intArray;
        public long[] longArray;
        public double[] doubleArray;
        public float[] floatArray;
        public short[] shortArray;
        public byte[] byteArray;
        public boolean[] booleanArray;
        public char[] charArray;

        public AllPrimitiveArraysObject() {}

        public AllPrimitiveArraysObject(int[] intArray, long[] longArray, double[] doubleArray,
                                         float[] floatArray, short[] shortArray, byte[] byteArray,
                                         boolean[] booleanArray, char[] charArray) {
            this.intArray = intArray;
            this.longArray = longArray;
            this.doubleArray = doubleArray;
            this.floatArray = floatArray;
            this.shortArray = shortArray;
            this.byteArray = byteArray;
            this.booleanArray = booleanArray;
            this.charArray = charArray;
        }
    }

    // Map test classes

    public static class StringIntegerMapObject {
        public Map<String, Integer> map;
        public StringIntegerMapObject() {}
        public StringIntegerMapObject(Map<String, Integer> map) { this.map = map; }
    }

    public static class IntegerStringMapObject {
        public Map<Integer, String> map;
        public IntegerStringMapObject() {}
        public IntegerStringMapObject(Map<Integer, String> map) { this.map = map; }
    }

    public static class IntegerIntegerMapObject {
        public Map<Integer, Integer> map;
        public IntegerIntegerMapObject() {}
        public IntegerIntegerMapObject(Map<Integer, Integer> map) { this.map = map; }
    }

    public static class LongDoubleMapObject {
        public Map<Long, Double> map;
        public LongDoubleMapObject() {}
        public LongDoubleMapObject(Map<Long, Double> map) { this.map = map; }
    }

    public static class MixedPrimitiveAndMapObject {
        public int intValue;
        public Map<String, Integer> map;

        public MixedPrimitiveAndMapObject() {}

        public MixedPrimitiveAndMapObject(int intValue, Map<String, Integer> map) {
            this.intValue = intValue;
            this.map = map;
        }
    }

    // ========== Nested Object Test Classes ==========

    public static class Point {
        public int x;
        public int y;

        public Point() {}

        public Point(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }

    public static class Rectangle {
        public Point topLeft;
        public Point bottomRight;
        public int color;

        public Rectangle() {}

        public Rectangle(Point topLeft, Point bottomRight, int color) {
            this.topLeft = topLeft;
            this.bottomRight = bottomRight;
            this.color = color;
        }
    }

    public static class SimpleNestedObject {
        public int value;
        public IntObject nested;

        public SimpleNestedObject() {}

        public SimpleNestedObject(int value, IntObject nested) {
            this.value = value;
            this.nested = nested;
        }
    }

    public static class MultiNestedObject {
        public int id;
        public IntObject intNested;
        public DoubleObject doubleNested;
        public long timestamp;

        public MultiNestedObject() {}

        public MultiNestedObject(int id, IntObject intNested, DoubleObject doubleNested, long timestamp) {
            this.id = id;
            this.intNested = intNested;
            this.doubleNested = doubleNested;
            this.timestamp = timestamp;
        }
    }

    public static class DeepNestedLevel3 {
        public int level3Value;

        public DeepNestedLevel3() {}

        public DeepNestedLevel3(int level3Value) {
            this.level3Value = level3Value;
        }
    }

    public static class DeepNestedLevel2 {
        public int level2Value;
        public DeepNestedLevel3 level3;

        public DeepNestedLevel2() {}

        public DeepNestedLevel2(int level2Value, DeepNestedLevel3 level3) {
            this.level2Value = level2Value;
            this.level3 = level3;
        }
    }

    public static class DeepNestedLevel1 {
        public int level1Value;
        public DeepNestedLevel2 level2;

        public DeepNestedLevel1() {}

        public DeepNestedLevel1(int level1Value, DeepNestedLevel2 level2) {
            this.level1Value = level1Value;
            this.level2 = level2;
        }
    }
}
